### ISSUE TITLE
Not working on platform

### ISSUE THREAD

**Issue by javmarquez13** [ied206/ManagedWimLib#3]
Hi ied206

I have this issue when i try to run the application

![image](https://user-images.githubusercontent.com/28401144/114240134-46d32280-9944-11eb-9b75-ae5dab543393.png)

Could you help ?

Thanks in advance!

**Comment by ied206** [comment]
You must call `Wim.GlobalInit()` with a path to dll file on Windows. Parameterless `GlobalInit()` tries to use a system-installed library file, which is supported only on Linux.

Look [USAGE.md](https://github.com/ied206/ManagedWimLib/blob/3dc19678418940e0dd8008531d565a15b8fd7d04/USAGE.md#initialization) for how to find a dll path.
